# You are given two strings s and t.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Return the letter that was added to t.

dense_arr_size = 26 + 97


class Solution:
    def findTheDifference(self, s: str, t: str):
        counts = [0] * dense_arr_size
        i = 0
        while i < len(s):
            counts[ord(s[i])] += 1
            counts[ord(t[i])] -= 1
            i += 1
        counts[ord(t[-1])] -= 1

        for i in range(97, dense_arr_size):
            if counts[i] == -1:
                return chr(i)


# expect "e"
print(Solution().findTheDifference("abcd", "abcde"))

# reflection: knowing something about your input data can allow optimizations based off the
# bounds. In this example, I knew characters would always be lowercase alphabetic, so a dense
# array was possible based off their ascii values
