# You are given two strings s and t.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Return the letter that was added to t.


class Solution:
    def findTheDifference(self, s: str, t: str):
        counts = [0] * 26
        i = 0
        while i < len(s):
            counts[ord(s[i]) - 97] += 1
            counts[ord(t[i]) - 97] -= 1
            i += 1
        counts[ord(t[-1]) - 97] -= 1

        for i, n in enumerate(counts):
            if n == -1:
                return str(chr(i + 97))


# expect "e"
print(Solution().findTheDifference("abcd", "abcde"))
