# You are given two strings s and t.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Return the letter that was added to t.


class Solution:
    def findTheDifference(self, s: str, t: str):
        counts = [0] * (26 + 97)
        i = 0
        while i < len(s):
            counts[ord(s[i])] += 1
            counts[ord(t[i])] -= 1
            i += 1
        counts[ord(t[-1])] -= 1

        # python quirk: enumerate is actually faster than doing a range() to get an index because enumerate drops down to a C level loop,
        # and indexing a python array does extra checks to ensure the index is in range.
        # So enumerating over the whole list is actually faster than starting in the middle with a range (facepalm)
        for i, n in enumerate(counts):
            if n == -1:
                return chr(i)


# expect "e"
print(Solution().findTheDifference("abcd", "abcde"))

# reflection: knowing something about your input data can allow optimizations based off the
# bounds. In this example, I knew characters would always be lowercase alphabetic, so a dense
# array was possible based off their ascii values
